name: test1

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: prepare
        run: ./t/prepare.sh
      - name: test
        run: ./t/test1.sh
